apiVersion: v2
appVersion: 0.2.0
description: Automate ExternalIP entries for Kuberentes Services
home: https://github.com/spacebird-dev/charts
name: externalip-manager
sources:
- https://github.com/spacebird-dev/externalip-manager
type: application
version: 0.2.2
